name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.1.0

      - name: fmt
        run: deno fmt --check

      - name: lint
        run: deno lint --unstable

      - name: test
        run: deno test --allow-read --allow-write
